import styled from "styled-components";
import Image from "next/image";

import Head from "next/head";
import Header from "../components/Header";
import NavigationBar from "../components/NavigationBar/NavigationBar";
import ContentWrapper from "../components/ContentWrapper";

import Bread from "/public/assets/icons/bread.svg";

const categories = [
  { name: "Obst & Gemüse", icon_src: "/assets/icons/watermelon.svg" },
  { name: "Haushalt", icon_src: "/assets/icons/spray.svg" },
  { name: "Backwaren", icon_src: "/assets/icons/bread.svg" },
];

export default function Categories() {
  console.log(Bread);
  return (
    <>
      <Head>
        <title>Kategorien</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>Kategorien</Header>
      <main>
        <ContentWrapper>
          <CategoryContainer>
            {categories.map(({ name, icon_src }) => (
              <StyledButton key={name}>
                <span>{name}</span>
                <Image src={icon_src} width={24} height={24} />
              </StyledButton>
            ))}
          </CategoryContainer>
        </ContentWrapper>
      </main>
      <NavigationBar />
    </>
  );
}

const CategoryContainer = styled.div`
  background-color: var(--list-secondary);
  width: 100%;
  height: 73vh;
  padding: 1rem;
`;

const StyledButton = styled.button`
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 0.2rem;
  background-color: var(--list-primary);
  margin: 0.5rem 0;
  border-radius: 0.5rem;
  border: none;
  box-shadow: var(--button-shaddow);
`;
