import styled from "styled-components";
import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

import Header from "../components/Header";
import NavigationBar from "../components/NavigationBar/NavigationBar";
import ContentWrapper from "../components/ContentWrapper";
import BackToAllButton from "../components/buttons/BackToAllButton";
import { getCurrentCategories } from "../services/shoppingItemService";

export async function getServerSideProps() {
  const categories = await getCurrentCategories();
  return {
    props: { categories: categories },
  };
}

export default function Categories({ categories }) {
  return (
    <>
      <Head>
        <title>Kategorien</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>Kategorien</Header>
      <main>
        <ContentWrapper>
          <CategoryContainer>
            {categories.map(({ name, icon_src }) => (
              <StyledButton key={name}>
                <span>{name}</span>
                <Image src={icon_src} width={30} height={30} />
              </StyledButton>
            ))}
          </CategoryContainer>
          <Link href={"/"} passHref>
            <StyledLink>
              <BackToAllButton />
            </StyledLink>
          </Link>
        </ContentWrapper>
      </main>
      <NavigationBar />
    </>
  );
}

const StyledLink = styled.a`
  align-self: flex-start;
  text-decoration: none;
`;

const CategoryContainer = styled.div`
  background-color: var(--list-secondary);
  width: 100%;
  align-self: center;
  height: 100%;
  padding: 1rem;
  border: solid 1px #b3b3b3;
  border-radius: 0.5rem;
  overflow-y: auto;
`;

const StyledButton = styled.button`
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 0.6rem;
  background-color: var(--list-primary);
  margin: 1rem 0;
  border-radius: 0.5rem;
  border: none;
  box-shadow: var(--button-shaddow);
  font-family: "Noto Sans";
  font-size: 1.2rem;
  font-weight: bold;

  &:first-child {
    margin-top: 0;
  }
`;
