import { Scatter } from "react-chartjs-2";
import { Chart as ChartJS, registerables } from "chart.js/auto";
import "chartjs-adapter-luxon";
import Head from "next/head";

import Header from "../components/Header";
import NavigationBar from "../components/NavigationBar/NavigationBar";
import ContentWrapper from "../components/ContentWrapper";
import { getAllExpenses } from "../services/expensesService";

export async function getServerSideProps() {
  const expenses = await getAllExpenses();
  return {
    props: { expenses: expenses },
  };
}

export default function Expenses({ expenses }) {
  const data = expenses.map((expense) => ({
    x: new Date(expense.date),
    y: expense.amount,
  }));

  const sortedData = data.sort(
    (dataPointPre, dataPointPost) =>
      Number(dataPointPre.x) - Number(dataPointPost.x)
  );

  const plotOptions = {
    scales: {
      y: {
        beginAtZero: true,
        title: {
          display: true,
          text: "Ausgaben | € |",
          font: {
            size: "15rem",
          },
        },
        grid: {
          display: false,
        },
      },
      x: {
        type: "time",
        time: {
          // Luxon format string
          //tooltipFormat: "DD MM",
        },
        title: {
          display: true,
          text: "Datum",
          font: {
            size: "15rem",
          },
        },
        grid: {
          display: false,
        },
      },
    },
    plugins: {
      legend: {
        display: false,
      },
    },
  };

  const plotData = {
    datasets: [
      {
        data: data,
        backgroundColor: "rgba(11, 158, 91, 0.5)",
        borderColor: "#0B7D54",
        borderWidth: 2,
        showLine: true,
      },
    ],
  };

  return (
    <>
      <Head>
        <title>Ausgaben</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>Ausgaben</Header>
      <main>
        <ContentWrapper>
          <Scatter options={plotOptions} data={plotData} />
        </ContentWrapper>
      </main>
      <NavigationBar />
    </>
  );
}
