import { nanoid } from "nanoid";
import { useState } from "react";

import Head from "next/head";
import ShoppingList from "../components/ShoppingList";

export default function Home() {
  const [shoppingListItems, setShoppingListItems] = useState(shoppingListDB);

  return (
    <>
      <Head>
        <title>MyShoppingManager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>MyShoppingManager</h1>
        <ShoppingList items={shoppingListItems} />
      </main>
    </>
  );
}

const SHOPPING_LIST_DB = [
  {
    id: nanoid(),
    name: "Brot",
    checked: false,
  },
  {
    id: nanoid(),
    name: "Bananen",
    checked: false,
  },
  {
    id: nanoid(),
    name: "Marmelade",
    checked: false,
  },
  {
    id: nanoid(),
    name: "Milch",
    checked: true,
  },
  {
    id: nanoid(),
    name: "Salat",
    checked: true,
  },
];
